### ISSUE TITLE
VCS directory present: .git

### ISSUE THREAD

**Issue by chorny** [wfso/Mojolicious-ServiceManage#1]
You accidentally packed your repository into distribution. It takes space in CPAN mirrors. Please remove it.
Build tool for WFSO/Mojolicious-Services-1.0.0.tar.gz was detected as ExtUtils::MakeMaker.
To remove repository directory you need to:
- Upgrade ExtUtils::MakeMaker to latest version.
- Remove .git directory and any files in it from MANIFEST and add regex for .git to MANIFEST.SKIP (if exists).
- Create your distribution for CPAN with your build tool: `make dist` (dmake on Windows).
- Delete old versions from PAUSE, especially versions listed here: http://cpanold.chorny.net/?a=WFSO

P.S. This report was generated automatically.

**Comment by wfso** [comment]
处理完成
